import "server-only";
import crypto from "crypto";
import usersData from "./users.data.json";

// ============================================================================
// USER ROSTER (server-only).
//
// users.data.json holds ONLY salted password hashes + scenario assignments —
// no plaintext passwords. It is generated by scripts/gen-roster.mjs, which also
// writes the instructor handout ROSTER.md (git-ignored) with the plaintext
// passwords and each user's expected flags.
//
// Password hash scheme: scrypt(password, salt) -> hex.  Verified in constant
// time. Salts are per-user random.
// ============================================================================

export type StoredUser = {
  username: string;
  salt: string; // hex
  hash: string; // hex scrypt(password, salt, 32)
  scenarios: string[]; // 4 scenario ids
};

const USERS: StoredUser[] = usersData as StoredUser[];
const BY_NAME = new Map(USERS.map((u) => [u.username.toLowerCase(), u]));

const SCRYPT_KEYLEN = 32;

export function findUser(username: string): StoredUser | undefined {
  return BY_NAME.get(username.trim().toLowerCase());
}

export function verifyPassword(user: StoredUser, password: string): boolean {
  const derived = crypto.scryptSync(password, Buffer.from(user.salt, "hex"), SCRYPT_KEYLEN);
  const stored = Buffer.from(user.hash, "hex");
  if (derived.length !== stored.length) return false;
  return crypto.timingSafeEqual(derived, stored);
}

// Used by gen-roster (and tests) to produce a hash for a known password.
export function hashPassword(password: string, saltHex: string): string {
  return crypto
    .scryptSync(password, Buffer.from(saltHex, "hex"), SCRYPT_KEYLEN)
    .toString("hex");
}

export function userScenarios(username: string): string[] {
  return findUser(username)?.scenarios ?? [];
}
